version: '3.8'
services:
  landing-page:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped